### ISSUE TITLE
Suggestion: Don't allow all the users to create new tags

### ISSUE THREAD

**Issue by shivasagarrao** [GATEOverflow/question2answer#10]
Currently any user in https://csedoubts.gateoverflow.in/ can create new tags. This is leading to lot of redundant tags. If a user want to correctly tag a question, I think most of the tags are already available. So my suggestion would be to allow creating new tags only for people who have for example >500 points.

**Comment by arjunsuresh** [comment]
Actually that is already in place and minimum points required for creating new tags is 1000. Has anyone below this created a tag recently?

https://csedoubts.gateoverflow.in/tags
Meanwhile if you find any tag which needs to be deleted or merged with any other tag you can submit that as a list here like below. If a tag "c" needs to be deleted just add that in a new line. If a tag "a" needs to be replaced with tag "b", "a,b" can be added in a new line like given below.

a,b
c

**Comment by shivasagarrao** [comment]
> Actually that is already in place and minimum points required for creating new tags is 1000. Has anyone below this created a tag recently?

I don't know there was a minimum limit of points. I got this doubt because there were lot of tags starting with `#` which are mostly created by new users. 
Remove all the tags which are starting with `#` and I think all the tags which are only tagged once can be removed. 

Tags in https://csedoubts.gateoverflow.in/tags

computernetwork, computer-networks
computernetworks, computer-networks
selfdoubt, self-doubt
madeeasy-workbook, made-easy-workbook
discrete-maths, discrete-mathematics
gatesyllabus, syllabus-doubt
madeeasy-workbook, made-easy-workbook
c-programming-for-gate, programming-in-c
madeeasytestseries, made-easy-test-series
datalinklayer, data-link-layer
networks
tcpheader
theory
computation
operatingsystem
plzz
solve
fork-system-call, fork
os
typesofos
cn
asymptotic
cd
limit
key
workbook
#toc      
-32que
madeeasytest
grammer
2014
binary
closureproperties
regularlanguage

---

I think all the tags are same in both https://csedoubts.gateoverflow.in/ and https://gateoverflow.in/ so if you remove/modify tags in https://csedoubts.gateoverflow.in/ will it also reflect in https://gateoverflow.in/ ?

**Comment by arjunsuresh** [comment]
Actually they are not same on both sites and we have to consider them separate. I have now removed these tags from both sites.
