### ISSUE TITLE
GATE 2022 Civil Set 2 ( for technical questions), title should be same as Set 1 

### ISSUE THREAD

**Issue by Patel230** [GATEOverflow/question2answer#14]
This is set 1 from Civil GATE 2022.
![image](https://user-images.githubusercontent.com/17196758/159395623-970bff1a-11d1-460d-9d72-f215c668b472.png)
This is set 2 from Civil GATE 2022
![image](https://user-images.githubusercontent.com/17196758/159395692-36ffd9fd-b88e-4e4e-950f-49920d58b38f.png)
Please change the name of the title of GATE 2022 Civil Set 2.

**Comment by arjunsuresh** [comment]
Fixed now

**Comment by Patel230** [comment]
Thank you so much sir.
