### ISSUE TITLE
Title needs to change. 

### ISSUE THREAD

**Issue by Patel230** [GATEOverflow/question2answer#18]
https://gateoverflow.in/tag/nielit2022jan-scientistb

Sir, please change the date from "January" to "April."

For verification of purpose, please use this blog https://gateoverflow.in/blog/10177/previous-year-nielit-papers and  https://nielit.gov.in/delhi/content/previous-question-papers-recruitment-exam

**Comment by arjunsuresh** [comment]
Changed now
