### ISSUE TITLE
FEATURE REQUEST : Exit from the discussion

### ISSUE THREAD

**Issue by csemasthan** [GATEOverflow/question2answer#2]
when we are commented on either answer or blog, the subsequent comments are notified us. But after sometime, if we're not interested in the discussion, we can't avoid the notifications.

there should be a button to exit from the discussion. Similar way, we need Join button to discussion ( either notification count or mail or sometime both ) without commenting on that thread.

**Comment by shivasagarrao** [comment]
> when we are commented on either answer or blog, the subsequent comments are notified us. But after sometime, if we're not interested in the discussion, we can't avoid the notifications.
> 
> there should be a button to exit from the discussion.

This feature is currently unavailable in GO site and need to be implemented.

> Similar way, we need Join button to discussion ( either notification count or mail or sometime both ) without commenting on that thread.

![AVEN_Follow](https://user-images.githubusercontent.com/85158834/120295517-d1048b00-c2e4-11eb-9eae-84bf6313592b.png)


If you click on "Follow" you can get notification email for all answers/comments. But there is a problem. It gives notification email for all the answers/comments. If you want to only get notification for specific thread where you have commented it's not possible. I think your feature request might be to get notification specific thread where you have commented.

**Comment by csemasthan** [comment]
Feature Implemented.
