### ISSUE TITLE
FEATURE REQUEST : private messages

### ISSUE THREAD

**Issue by csemasthan** [GATEOverflow/question2answer#3]
present in the site, we have only turn on or turn off private messages. But if we have a option like, receive messages based on categories
i) editors, moderators, admin 
ii) some specific users
iii) points grater than 

then it will be some more useful.

**Comment by arjunsuresh** [comment]
Now we have an option to receive messages only from those in our circle. So can this issue be closed now?

**Comment by csemasthan** [comment]
yes, we can close.
