### ISSUE TITLE
FEATURE REQUEST : Reject a post with remarks

### ISSUE THREAD

**Issue by csemasthan** [GATEOverflow/question2answer#4]
present in the site, we have only either approve or reject a post. But if we have a comment box to write remarks whenever we want to reject a post, then it will be useful to understand why the post is rejected to the person who posted it.

**Comment by arjunsuresh** [comment]
Feature request since a year - no developer found yet. https://www.question2answer.org/qa/85718/reject-with-a-reason-plugin-request

**Comment by arjunsuresh** [comment]
This option is now available for moderators. Shall this issue be closed?

**Comment by csemasthan** [comment]
yes 👍
