### ISSUE TITLE
Feature Request: Add Icons for Mark As Read, Lists and Follow in SnowFlat Theme

### ISSUE THREAD

**Issue by shivasagarrao** [GATEOverflow/question2answer#5]
Screenshot of Mobile using SnowFlat Theme:

![SnowFlat_Mobile](https://user-images.githubusercontent.com/85158834/120304304-4d02d100-c2ed-11eb-9bc0-a1cd6332658b.png)

---

Screenshot of Desktop using SnowFlat Theme:

![SmowFlat_Desktop](https://user-images.githubusercontent.com/85158834/120304114-1af16f00-c2ed-11eb-9e0e-cbc7d818feca.png)

As you can see in the above images it is almost impossible to know which button does what in mobile. Atleast in desktop tooltips will be displayed when we hover it. So add **Icons** for Mark As Read, Lists and Follow in SnowFlat Theme.

**Comment by arjunsuresh** [comment]
This is fixed now
