### ISSUE TITLE
Bug: LaTeX equations are small in SnowFlat theme in mobile

### ISSUE THREAD

**Issue by shivasagarrao** [GATEOverflow/question2answer#7]
![Donut_LaTeX](https://user-images.githubusercontent.com/85158834/120306781-da472500-c2ef-11eb-8135-b549312f7968.png)

Above screenshot is Donut theme in mobile.

---
![SnowFlat_LaTeX](https://user-images.githubusercontent.com/85158834/120306792-dddaac00-c2ef-11eb-8cce-1ee9506acb59.png)

Above screenshot is SnowFlat theme in mobile. 
As you can see size of LaTeX equations are small in SnowFlat theme in mobile when compared to Donut theme in mobile. There is **NO** issue of size of LaTeX equations in SnowFlat theme in desktop.

**Comment by arjunsuresh** [comment]
Snowflat theme is not the default one. So closing this for now.
