### ISSUE TITLE
Bug: Can't Flag and Recategorize a question in MobileX Theme in Desktops & Laptops

### ISSUE THREAD

**Issue by shivasagarrao** [GATEOverflow/question2answer#8]
![flag_question_MobileX](https://user-images.githubusercontent.com/85158834/120480833-17cdb000-c3cd-11eb-8a65-cfe3d3cfbb80.png)

You can see in the above screenshot there is no option to either Flag or Recategorize a question in MobileX Theme. This issue is **NOT** there in mobiles.

**Comment by arjunsuresh** [comment]
Actually this theme is only meant for mobile.

**Comment by shivasagarrao** [comment]
![Mobile_X](https://user-images.githubusercontent.com/85158834/122669498-4d4f0780-d1db-11eb-8c03-cc7e92976199.png)

Small suggestion sir. If Mobile X theme is only meant for mobiles then display it only in `Choose mobile theme ` but NOT in `Choose theme` in the above screenshot which is taken from account settings page https://gateoverflow.in/account . This helps to choose only the themes which are suitable for mobiles/desktops.

**Comment by arjunsuresh** [comment]
Yes. Unfortunately that means adding a new setting to all themes -- this option is currently not present in Q2A themes.

**Comment by arjunsuresh** [comment]
This is now implemented
