### ISSUE TITLE
Bug: Mark for read and Follow this question are being incorrectly displayed in few themes

### ISSUE THREAD

**Issue by shivasagarrao** [GATEOverflow/question2answer#9]
![Candy](https://user-images.githubusercontent.com/85158834/120481990-4e57fa80-c3ce-11eb-8c46-5f2d4e8a366d.png)
Above screenshot is Candy theme.

---

![Classic](https://user-images.githubusercontent.com/85158834/120481996-4f892780-c3ce-11eb-8303-2dab08b767e3.png)
Above screenshot is Classic theme.

---

![Diligent](https://user-images.githubusercontent.com/85158834/120482001-5021be00-c3ce-11eb-9927-074ce78a0df7.png)
Above screenshot is Diligent theme.

---

![Snow](https://user-images.githubusercontent.com/85158834/120482005-50ba5480-c3ce-11eb-8988-1d704566796b.png)
Above screenshot is Snow theme.

---

You can see that this issue is present in Candy, Classic, Diligent, Snow themes. Both Mark for read and Follow this question are being incorrectly displayed as 313510 as shown in the above screenshots.

**Comment by arjunsuresh** [comment]
Fixed, thanks to @pupi https://www.question2answer.org/qa/93792/right-way-to-pass-value-using-button-click-on-question-page
